on:
  push:
    branches:
      - apt-base

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get or create tag
        id: get_tag
        run: |
          TAG="apt-base-release"
          if git show-ref --tags $TAG; then
            echo "tag=$TAG" >> $GITHUB_OUTPUT
          else
            git tag $TAG
            echo "tag=$TAG" >> $GITHUB_OUTPUT
          fi

      - name: Create or update Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_tag.outputs.tag }}
          release_name: Release ${{ steps.get_tag.outputs.tag }}
          body: |
            Aggiornamento della release
          draft: false
          prerelease: false
        if: github.event_name == 'push'
